version: '3'
services:
  db:
    image: mysql:8.0.23
    restart: always
    volumes:
    - ./initdb-scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
    - db_network
  db-monitor:
    image: phpmyadmin/phpmyadmin:5.1.0
    restart: always
    ports:
    - "8000:80"
    environment:
      PMA_HOSTS: db
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
    - db_network
  backend:
    image: golang
    tty: true
    volumes:
    - ./backend:/go/src/app
    environment:
      dbpath: ${MYSQL_DATABASE}
      dbpassword: ${MYSQL_ROOT_PASSWORD}
    networks:
    - api_network
    - db_network
  frontend:
    build: .
    tty: true
    volumes:
    - ./frontend:/root/lo_tracker
    networks:
    - api_network
networks:
  api_network: {}
  db_network: {}